modLoader="javafml"
loaderVersion="[43,)"
license="LGPLv2.1"
[[mods]]
modId="classicraft"
version="${file.jarVersion}"
displayName="Classicraft Mod"
logoFile="classicraft.png"
authors="Nameless, 1798643961"

description = '''

'''

[[dependencies.classicraft]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.classicraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.classicraft]]
    modId="toughasnails"
    mandatory=true
    versionRange="[8.0.0.78]"
    ordering="NONE"
    side="BOTH"

[[dependencies.classicraft]]
    modId="sereneseasons"
    mandatory=true
    versionRange="[8.1.0.24]"
    ordering="NONE"
    side="BOTH"