modLoader="javafml"
loaderVersion="[45,)"
license="GPLv2.0"
[[mods]]
modId="classicraft"
version="${file.jarVersion}"
displayName="Classicraft Mod"
logoFile="classicraft.png"
authors="Vapour_Beatle"
credits="TT432, Glyceryl6, Thaumstrial, 1798643961, wdog5"

description = '''
A Vanilla Expandation mod
'''

[[dependencies.classicraft]]
modId="forge"
mandatory=true
versionRange="[45,)"
ordering="NONE"
side="BOTH"

[[dependencies.classicraft]]
modId="minecraft"
mandatory=true
versionRange="[1.19.4,1.20)"
ordering="NONE"
side="BOTH"

[[dependencies.classicraft]]
modId="geckolib"
mandatory=true
versionRange="[3.0.9,4.0.5)"
ordering="NONE"
side="BOTH"